N_sim_batch: 500 #check 1000 to get shorter garbage collection. 
N_episode_length: 20 #number of periods on simulated paths
N_epochs_per_episode: 1
N_minibatch_size: 500 #when close to optimum, 2000 is better than 1000. 5000 gives problem of slow adaptation to a moving target (after 2 gradient steps new trajectories are generated)
N_episodes: 5000 #5000 or 10000
keras_precision: float32
expectation_type: monomial #monomial (more efficient) or pseudo_random as alternative
sorted_within_batch: false
expectation_pseudo_draws: 50 #5 in readme file. This should not be lower than 50 according to Simon, (applies to pseudo-random)
N_simulated_episode_length: 80 #Frank: I added this, is compiled by parameters.py and used in post_process.py (initially this was 10000)
N_simulated_batch_size : 10 #Frank: I added this, is compiled by parameters.py and used in post_process.py (initially this was 1)