N_sim_batch: 500
N_episode_length: 300 #number of periods on simulated paths
N_epochs_per_episode: 1
N_minibatch_size: 500
N_episodes: 20 #5000 or 10000
keras_precision: float32
expectation_type: pseudo_random #pseudo_random or monomial #monomial [1,1] gives 4 cases: shock of 0.7,0;-0.7,0;0,0.7,0,-0.7 i.e. it assumes only 2 values for a shock and if there are 2 different shocks, they cannot happen at the same time
sorted_within_batch: false
expectation_pseudo_draws: 5
N_simulated_episode_length: 80 #Frank: I added this, is compiled by parameters.py and used in post_process.py (initially this was 10000)
N_simulated_batch_size : 10 #Frank: I added this, is compiled by parameters.py and used in post_process.py (initially this was 1)