N_sim_batch: 200 #this cannot be changed between runs in the same hydra directory #Old value 500
N_episode_length: 200 #number of periods on simulated paths #100, 120, 140, 160
N_epochs_per_episode: 1 #if this is 2, the simulated data is used twice for calculating gradients and to update weights
N_minibatch_size: 200 #this is the number of obs to calculate the gradient and update weights (so 200*150/600=50 updates per episode)  #old value 500
N_episodes: 5000 #5000 or 10000
keras_precision: float32
expectation_type: monomial #monomial or pseudo_random as alternative
sorted_within_batch: false #if true, a minibatch has consecutive periods. a minibatch with only intial or long term periods would be bad.
expectation_pseudo_draws: 10 # only for pseudo_random
N_simulated_episode_length: 75 #Frank: I added this, is compiled by parameters.py and used in post_process.py (initially this was 10000)
N_simulated_batch_size : 100 #Frank: I added this, is compiled by parameters.py and used in post_process.py (initially this was 1)