constants: 
#production function
    delta: 0.04 
    alpha: 0.3
    epsilon_f: -4
    varphi_f: 0.99999016
    varphi_E: 9.84e-06
    sigma0: 2
    varphi_c: 0.304
    varphi_d: 0.696
    xi : 0.01
    chi : 1
    chi_s : 4 
    A0: 8.76
    L0: 8.14
    vareps: 300
    vareps2: 0.004
    
#utility and discounting
    eta : 1.35
    r : 0.0351
    g : 0.02
    g_L : 0.0029
    g_tau : 0.015
    RRA : 1.35
    dt : 1.0 
    
#Technical change, emissions and abatement costs
    omega : 0.5
    varrho: 0.7
    g_epsilon : 0.027
    M0 : 36
    P_BAU : 57

#stranding costs
    psi1 : 5.94 # set to 5.98
    psi2 : 0.766
    psi3 : 1.13 #set to 2.06
    g_psi : 0.01  #should be equal to g+g_L

#climate and damages
    zeta : 0.0006
    gamma : 0.0154
    
#scaling to obtain states and policies close to [0,1]. Definitions.x=s_scale * State.x
    kf_scale : 1 #scale initial distribution AND kf0 if scale changes!
    ks_scale : 0.01 #Max ks is 0.026
    v_scale  : 100 
    id_scale : 0.01 #scale boundaries if scale changes!
    ic_scale : 0.1 #scale boundaries if scale changes!
    lambdaks_scale : 1 #scale boundaries if scale changes! lambdaks should be between -0.013 and -0.001

###ONLY IN EQUATIONS.PY    
#initial states (used in postprocess)
    kf0 : 4.8 #should be scaled.
    kc0 : 0.119
    kd0 : 0.614
    ks0 : 0
    T0  : 1.38 
    tau0: 0
#min & max of states (including steady states)
    kf_max : 5.5 #unscaled
    kf_min : 3.4 #unscaled
    kc_max : 1.4
    kc_min : 0.09 
    kd_max : 0.65
    kd_min : 0.00001
    T_max : 2.7 
    
###ONLY IN DYNAMICS.PY
#Uncertainty
    Sigmak : 0.0001 #temporary value was 1e-4 => sqrt(Sigmak)=1% is the standard deviation. In old paper sd=0.013 => Sigmak=0.000169
    SigmaS : 0.0007 #0.0009 #temporary value was 1e-6 => standard deviation = 0.1%. In old paper sd=0.03=3% => SigmaS=0.0009
    


