constants: 
#production function
    delta: 0.04 
    alpha: 0.3
    epsilon_f: -4
    varphi_f: 0.999953052
    varphi_E: 4.694e-5
    sigma0: 2
    varphi_c: 0.304
    varphi_d: 0.696
    xi : 0.01
    chi : 1
    chi_s : 5 
    A0: 8.76
    L0: 8.14
    vareps: 300
    vareps2: 0.004
    
#utility and discounting
    eta : 1.35
    r : 0.0351
    g : 0.02
    g_L : 0.0029
    g_tau : 0.015
    RRA : 1.35
    dt : 1.0 
    
#Technical change, emissions and abatement costs
    omega : 0.5
    varrho: 0.1
    g_epsilon : 0.027
    M0 : 36
    P_BAU : 57

#stranding costs
    psi1 : 5.94
    psi2 : 0.77
    psi3 : 1.13
    g_psi : 0.01

#climate and damages
    zeta : 0.0006
    gamma : 0.0154
    
#scaling to obtain states and policies close to [0,1]. Definitions.x=s_scale * State.x
    kf_scale : 1 #scale initial distribution AND kf0 if scale changes!
    ks_scale : 0.01 #Max ks is 0.036
    v_scale  : 100 
    id_scale : 0.01 #scale boundaries if scale changes!
    ic_scale : 0.1 #scale boundaries if scale changes!
    lambdaks_scale : 1 #scale boundaries if scale changes! lambdaks should be between -0.013 and -0.001

###ONLY IN EQUATIONS.PY    
#initial states (used in postprocess)
    kf0 : 4.39 #should be scaled.
    kc0 : 0.149
    kd0 : 0.770
    ks0 : 0
    T0  : 1.38 
    tau0: 0
#min & max of states (including steady states)
    kf_max : 5.2 #unscaled
    kf_min : 3.2 #unscaled
    kc_max : 1.4 
    kc_min : 0.1 
    kd_max : 0.8
    kd_min : 0.00001
    T_max : 2.8 
#min and max of initial policies (should be larger than on optimal path because initial conditions are stochastic)
    if0_max : 0.33 
    if0_min : 0.21
    ic0_max : 0.036 #unscaled, 
    ic0_min : 0.017 
    id0_max : -0.010 #unscaled (applies to year 0) This is too strict for dt=4
    id0_min : -0.025 #unscaled (applies to year 0)
    lambdaks_max : -0.3 # lambda ks is around -0.67 in period zero, -0.2 in period 1, when ks=0.022 
    
###ONLY IN DYNAMICS.PY
#Uncertainty
    Sigmak : 0.0001 #temporary value was 1e-4 => sqrt(Sigmak)=1% is the standard deviation. In old paper sd=0.013 => Sigmak=0.000169
    SigmaS : 0.0007 #temporary value was 1e-6 => standard deviation = 0.1%. In old paper sd=0.03=3% => SigmaS=0.0009
    


